name = "lava/smart_contract"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'lava/smart_contract'"

[repository]
user = "lava"
project = "smart_contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.16"
source = "github"

[config]
